document.writeln("<!doctype html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>chicken dinner</title>");
document.writeln("<link rel=\'stylesheet\' href=\'../css/css.css\' type=\'text/css\'>");
document.writeln("");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<div class=\'hp\'>");
document.writeln("<ul class=\'menu\'>");
document.writeln(" <a href=\'../首页.html\'><img src=\'../source/logo.png\'></a>");
document.writeln("  <li><a href=\'../index.html\'>主页</a></li>	");
document.writeln("  <li><a href=\'GameIntroductioin.html\' >游戏介绍</a></li>");
document.writeln("  <li><a href=\'game play.html\'>游戏玩法</a></li> ");
document.writeln("  <li>");
document.writeln("  	<a>物品装备</a>");
document.writeln("  	<ul class=\'menu2\'>");
document.writeln("  		<li><a href=\'weapon.html\'>武器</a></li>");
document.writeln("  		<li><a href=\'vehicle.html\'>载具</a></li>");
document.writeln("  		<li><a href=\'supply.html\'>补给</a></li>");
document.writeln("  		<li><a href=\'parts for weapon.html\'>配件</a></li>");
document.writeln("  	</ul>");
document.writeln("  </li>");
document.writeln("  <li>");
document.writeln("  	<a>游戏地图</a> ");
document.writeln("  	<ul class=\'menu2\'>");
document.writeln("  		<li><a href=\'island.html\'>海岛</a></li>");
document.writeln("  		<li><a href=\'dessert.html\'>沙漠</a></li>");
document.writeln("  		<li><a href=\'forest.html\'>雨林</a></li>");
document.writeln("  	</ul>");
document.writeln("  </li>");
document.writeln("  <li><a href=\'game strategy.html\'>游戏攻略</a> </li>");
document.writeln("  <li><a href=\'effection.html\'>评价影响</a> </li>");
document.writeln("  <li><a href=\'team introduction.html\'>团队介绍</a> </li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("<div style=\'left: 0px; top: 0px;margin: 0px; padding: 0px; height:100%; width: 100%; z-index: -99; position: fixed;\'>");
document.writeln("	<img style=\'position: absolute; margin: 0px; padding: 0px; border: none;z-index: -999999; left:0px; \'src=\'../source/background/bgimg.jpg\'>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");